### ISSUE TITLE
Peer review feedback

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-rest-client-angular#11]
Application code feedback

- [x] Not sure the `Reader.java` class in `src/main/java/io/openliberty/guides/consummingrest/service/Reader.java` is needed. If not, it'd be clean up. 

- [x] All license header on the files that have been updated, should be changed to the current year, ie, `Copyright (c) 2019 IBM Corporation and others.` But looks like the service classes aren't changed from the previous version, they do not need changes. 

- [x] The application name in the `server.xml` file may need to be updated to more relevant to this guide. Currently having `io.openliberty.guides.consumingrest-ajs.war`, which is from the AngularJS server config file?

- [x] Same as above for the `<artifactId>io.openliberty.guides.consumingrest-ajs</artifactId>` in the `pom.xml`

- [x] Some comments in the `pom.xml` may need to be finalize? ie, 

```
<!-- NB! Set <version> to the latest released version of frontend-maven-plugin, like in README.md -->
```

Draft feedback

- [x] Consider update the `:guide-author: Open Liberty` field to the Author's name?

- [x] Consider adding the SEO title and description attributes in the `README.adoc` for this guide: 

```
:page-seo-title: Consuming RESTful web services with Angular
:page-seo-description: A tutorial on how to consume your microservices with Angular
```

- [x] Acrolinx (ID checker tool) suggestions: 
- spell "frontend" as "front end" for noun or "front-end" for adjective
- use contractions instead of the full form, ie, "do not" as "don't"
- simply word for "a variety of" to "various" 
- "This file will contain two classes: the service, which will handle data
access, and the component itself, which will handle presenting the data.The default
Angular application already contains a component.` => missing space after the first sentence
- change "class which" to "class, which" or "class that" 
- change "execute" to "run", "start" or "enter"

**Comment by realModusOperandi** [comment]
> Not sure the Reader.java class in src/main/java/io/openliberty/guides/consummingrest/service/Reader.java is needed. If not, it'd be clean up.

It's responsible for reading in the Artist JSON, so if it were to be removed, another way of deserializing the JSON would be necessary. Let me know what you want to do here.

> All license header on the files that have been updated, should be changed to the current year, ie, Copyright (c) 2019 IBM Corporation and others. But looks like the service classes aren't changed from the previous version, they do not need changes.

The only files that I have found with headers so far are the thee .java files that haven't changed, and the .adoc itself which has 2019 in the copyright year. What other files should I be adding copyright headers to?

> Consider update the :guide-author: Open Liberty field to the Author's name?

What should that name be? Especially considering this is a rework of an existing guide...

I will open a PR for the remaining items which I can change without additional questions.

**Comment by evelinec** [comment]
Thank you. The changes look good. 

After looking at the `Reader.java` class, it's fine to leave it. The copyright for the java classes are good as well. No changes needed. 

As with the `guide-author` field in the readme, we can use `Open Liberty`. 

Thank you.

**Comment by evelinec** [comment]
Fixed.
