### ISSUE TITLE
GK feedback for the Content review

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-rest-client-angular#13]
- [x] Switch the order of the first 2 introduction paragraphs
  - currently 
    - 1: "You'll learn ..."
    - 2: "Angular is ..."
  - suggestion:
    - 2: "Angular is ..."    
    - 1: "You'll learn ..."

- [x] the TypeScript link "https://typescriptlang.org" cannot be reached 
- [x] In the following statement, should use `and` between `responsive, intuitive` instead of comma?
  - "Angular helps you create responsive, intuitive applications..."

- [x] no need to have the JDK 9 dependencies in the pom.xml

- [x] failed on mac to run 'mvn install` at the start directory without change anything, but works fine on the finish directory
```
[INFO] --- frontend-maven-plugin:1.7.6:npm (npm run build) @ io.openliberty.guides.consumingrest-ng ---
[INFO] Running 'npm run build' in /Users/gkwan/tasks/CNAI/guides/testsite/guide-rest-client-angular/start/src/main/frontend
[INFO] 
[INFO] > frontend@0.0.0 build /Users/gkwan/tasks/CNAI/guides/testsite/guide-rest-client-angular/start/src/main/frontend
[INFO] > ng build --base-href="/app/"
[INFO] 
[ERROR] sh: ng: command not found
[ERROR] npm ERR! file sh
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno ENOENT
[ERROR] npm ERR! syscall spawn
[ERROR] npm ERR! frontend@0.0.0 build: `ng build --base-href="/app/"`
[ERROR] npm ERR! spawn ENOENT
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the frontend@0.0.0 build script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     /Users/gkwan/.npm/_logs/2019-05-15T17_33_23_849Z-debug.log
```
- [x] warning on linux when run `mvn install`
```
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/fsevents):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[ERROR] 
[INFO] added 1086 packages from 1026 contributors and audited 42611 packages in 33.519s
```

- [x] The instructions in "Update the app.module.ts file." and "Update the app.component.ts file." sections are not clear. Suggest to change "Update" to "Replace". Or do something like the "update" in the "Enabling explicit distributed tracing" section of  https://openliberty.io/guides/microprofile-opentracing.html 

- [x] Because the application is provided by the guide (i.e. the guide does not ask readers to create), better make content clear in use of the word "your". Suggest the following changes:
  - In the section "Importing the HTTP client", 
    - change "In the case of this guide, your application ..." to "...guide, the provided Angular application ..."
    - change "Your application is organized into a module..." to "The application is ..." or "The provided application is ..."
    - change "... into your module ..." to "... into the root module ..."
    - change "... from your application’s code." to "... from the application’s code."
  - In the section "Creating the Angular component",
    - change "You will create the component in your application..." to "You will need to create the Angular component in your application..."
    - change "This file ..."  to "The component file..."
    - change "The default Angular application ..." to "The provided Angular application ..."
    - change "First, import two classes you’ll need for the service: HttpClient and Injectable." to "First, import the `HttpClient` and `Injectable` classes for the artists service."
    - change "Finally, update the AppComponent class to use this service." to "Finally, update the AppComponent class to use the artists service."
    - Does the word "rest" in "...the rest of the application." mean "the part that is left after" or "REST service" or something?
    - Should "... on the promise and provide..." to "... on the Promise and provide..."?
  - In the section "Creating the Angular component template"
    - Can rewording the first whole statement "Now that ..."? It is not clear to me.
    - "Replace the template of your component." Why is a html file? In the context, As a reader, I think "component" is the app.component.ts.  Should say "Replace the template of the component HTML file."?
    - "this file" in  "The Angular application is already set up to display the contents of this file." means which file?
    - "Replace the Angular "Hello" HTML". As a reader, I do not realize what "Hello" HTML means or reference to which, because it is not mentioned in above content.
- [ ] page-seo-description should be improved

**Comment by evelinec** [comment]
FYI, I ran the same tests on my Mac environment, I didn't see the errors as described when testing in the `start` directory.

**Comment by realModusOperandi** [comment]
Responses to a couple items:

I've never seen the error on my system either, or on other systems where I test a fresh clone. Does it happen reliably?

The warning for Linux is expected--Angular specifies as an optional dependency a macOS-only package and when the platform isn't supported, npm issues the message as a warning. We could try removing the optional dependency but I believe that would be a departure from how most Angular environments are configured.

For page-seo-description, do you have a particular example of one I should look at? I minimally modified those values from the angularjs guide.

All other items I will address in the pull request.
