### ISSUE TITLE
artist vs artists

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/draft-guide-rest-client-angular#18]
Under "Creating the Angular component template", we have:

`The artists variable is bound to the artists member of the component.`

Should one of the `artists` be `artist`?

**Comment by evelinec** [comment]
@realModusOperandi would you like to assess this one? 

I think the first one should be `artist`.

**Comment by evelinec** [comment]
This is fixed in #21

**Comment by evelinec** [comment]
Verified fix on staging site.
