### ISSUE TITLE
Review feedback

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/draft-guide-rest-client-angular#19]
(1)

```
The class injects an instance of the HttpClient class, which it will use to request data from the REST API. It contains a constant ARTISTS_URL which points to the API endpoint it will request data from. Finally, it implements a method fetchArtists() that makes the request and returns the result.

To obtain the data for display on the page, fetchArtists() tries to use the injected http instance to perform a GET HTTP request to the ARTISTS_URL and returning the result. If an error occurs, it prints the message of the error to the console.
```

Looks like we default to localhost.  (Well, the service is local anyway.) . Useful to call this out and also indicate what needs to be done if the service isn't local.

(2)

```
Although this guide didn’t teach you how to build logic, you will likely build logic when you develop your own applications, and testing will become a crucial part of your development lifecycle. If you need to write test cases, follow the official unit testing and end-to-end testing documentation on the official Angular page.
```

It took me a while to parse "build logic".  Perhaps there is better way to phrase it.

**Comment by realModusOperandi** [comment]
For 1), I previously had the `https://localhost:9443` in the `ARTISTS_URL` but that was removed in a revision. Perhaps adding it back would make it more clear that the particular URL could be any URL accessible by the user's browser--there wouldn't be any other difference in the code.

2) Looks to be leftover language from the AngularJS tutorial. Perhaps something like "Although the Angular application this guide showed you how to build is very simple, when you build more complex Angular applications, testing will become a crucial..."?

**Comment by evelinec** [comment]
Verified the changes are on the staging site.

**Comment by evelinec** [comment]
@yeekangc do you want to take a look at the staging site and see if you're good with the changes? Thanks.

**Comment by yeekangc** [comment]
Took a quick look and I am fine with the changes that I saw.  Thank you, @evelinec.

Then, I don't think we have updated for (2)?  I am fine what what @realModusOperandi suggested above.

**Comment by evelinec** [comment]
@realModusOperandi would you make the changes for point (2) pls?

**Comment by realModusOperandi** [comment]
Underway

**Comment by evelinec** [comment]
Latest draft guide staging site has the updates for point (2) as below. This time I verified the correct paragraph other than the first one in this section. 

```
Although the Angular application this guide showed you how to build is very simple, when you build more complex Angular applications, testing will become a crucial part of your development lifecycle. If you need to write test cases, follow the official unit testing and end-to-end testing documentation on the official Angular page.
```

**Comment by evelinec** [comment]
Completed. Closed.
