### ISSUE TITLE
ID review for Consuming a RESTful web service with Angular

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/draft-guide-rest-client-angular#27]
I reviewed the Consuming a RESTful web service with Angular guide at https://draft-guides.mybluemix.net/guides/rest-client-angular.html, and I made my suggested updates in the attached Word doc. I had four questions about the content, and I highlighted those questions in the Word doc. 

Please feel free to reach out to me with any questions about my suggestions or to discuss the questions that I had. Thanks! 

[Angular Guide Comments.docx](https://github.com/OpenLiberty/draft-guide-rest-client-angular/files/3298629/Angular.Guide.Comments.docx)

**Comment by evelinec** [comment]
@Charlotte-Holt can you close this issue? Thanks

**Comment by Charlotte-Holt** [comment]
ID approved. Closing this issue.
