### ISSUE TITLE
Review feedback

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-rest-client-angular#5]
What you'll learn

- [x] It may be good to move the paragraph about Angular in "Angular is a framework for creating interactive web applications.." as the second paragraph in this section to explain right away what is Angular after the intro of the guide. 

- [x] In this section, try to explain why user wants to use Angular to cosume a RESTful web service? 

Importing the HTTP client

- [x] Navigate to the start directory to begin. => backtick `start` 

- [x] Angular applications consist of modules; each module declares all other modules that it imports or exports. AppModule is the root module, and most apps import HttpClientModule here. => This statement seem unclear, especially "most apps import HttpClientModule here" is confusing. Would be good to explain why `HttpClientModule` is imported here and/or what does it do?

Creating the Angular component

- [x] To obtain the data for display on the page, fetchArtists() Tries to use the injected http instance to perform a GET HTTP request to the ARTISTS_URL and returning the result.  
=> perhaps `fetchArtists()` method can have a hotspot
=> "Tries" should be lower case

- [x]  If an error occurs,it prints the message of the error to the console. => a space is needed after the comma 

- [x] the result of the HttpClient.get() method must be converted to a Promise using toPromise(). => the `toPromise()` can have a hotspot

- [x] To retrieve the data from the request, call then() on the promise and provide a function that will take in the data and store it to the artists class member. => the `artists` class can have a hotspot

Creating the Angular component template

- [x] The `app.component.html` file shows up empty on the code column. I think the problem is with the tags used in the `include` statement, in `include::finish/src/main/frontend/src/app/app.component.html[tags=html]`. There's no `html` tags defined in the `app.component.html` file, so no need to use the tags. You can see the draft guide content on our staging site at https://draft-guides.mybluemix.net/guides/rest-client-angular.html. 

- [x] Followed the guide to the following point (working in the `start` directory), the `http://localhost:9080/app` URL gives "Context root not found" error message.. 
```
After everything is set up, point your browser to the web application root http://localhost:9080/app to see the following output:

foo wrote 2 albums:
    Album titled album_one by foo contains 12 tracks
    Album tilted album_two by foo contains 15 tracks
bar wrote 1 albums:
    Album titled foo walks into a bar by bar contains 12 tracks
dj wrote 0 albums:
```

General application code

- [x] There are lots of files under the `src/main/frontend` directory, but only the `app.module.ts` and `app.component.ts` files are being described in the guide. What are the other files used for? Can some of them be cleaned up? 

- [ ] There are a number of files under `src/main/webapp/app` directory as well, and they're not being referred to in the guide. Are these files needed, and should be explained in the guide?

**Comment by evelinec** [comment]
> * [ ]  Followed the guide to the following point (working in the `start` directory), the `http://localhost:9080/app` URL gives "Context root not found" error message..
> 
> ```
> After everything is set up, point your browser to the web application root http://localhost:9080/app to see the following output:
> 
> foo wrote 2 albums:
>     Album titled album_one by foo contains 12 tracks
>     Album tilted album_two by foo contains 15 tracks
> bar wrote 1 albums:
>     Album titled foo walks into a bar by bar contains 12 tracks
> dj wrote 0 albums:
> ```

In fixing the above point, you added the following instructions: 
```
After everything is set up, if you have not started the REST service already, build and start both the REST service and the frontend by running the following command:

mvn install liberty:start-server

If the REST service is already running, compile only the frontend by running the following command:

mvn generate-resources
```

I think the first step of running the `mvn install liberty:start-server` is not needed, as the server is already started since the "Starting the service" section of the guide. Also user cannot just run this command again without stopping the server previously started, as that'll cause port conflict. I do understand the sentence says, "if you have not started the REST service already..", however, it's very easily for user to miss this message, and just run the command. If that's the case, they'll run into failure. I think we can get rid of this part: 
```
After everything is set up, if you have not started the REST service already, build and start both the REST service and the frontend by running the following command:

mvn install liberty:start-server
```
And change the following sentence: 
```
If the REST service is already running, compile only the frontend by running the following command:

mvn generate-resources
```
To: 
```
The Open Liberty server is already started, and the REST service is running. You can recompile the frontend by running the following command:

mvn generate-resources
```

What do you think?

**Comment by evelinec** [comment]
>  In this section, try to explain why user wants to use Angular to consume a RESTful web service?

For the above point, I saw that you added more explanation in the following paragraph: 

```
Angular is a framework for creating interactive web applications. Angular applications are written in HTML, CSS, and TypeScript, a variant of JavaScript. Angular’s template engine makes it easy to display and manipulate data in an intuitive manner, allowing you to quickly build a user interface for your REST services.
```

Can you also explain what is "Angular's template engine"? Is it used in this guide?

**Comment by realModusOperandi** [comment]
Re: The first comment, that change sounds good to me. Just something to jog their memory in case they don't have the server up at all.

For the second one, we are using the templating, but I think I want to change that paragraph some more. What would help me is, when we say "explain why the user wants to use Angular" what is the alternative they would be considering? Are these users who are comparing frontend frameworks? Are they just deciding whether to use a frontend framework at all? I could tune my explanation better if I know what to compare it to and what benefits to highlight.

**Comment by evelinec** [comment]
@realModusOperandi Thank you for the reply. We'll get back to you soon.

**Comment by evelinec** [comment]
Regarding "explain why the user wants to use Angular", I think describing what makes Angular standout is good. The latest changes in PR #8 seems good to me. Thanks a lot for making the changes.

**Comment by realModusOperandi** [comment]
Thanks for looking! I checked on the preview site and noticed a couple minor mistakes I made so I'll open a quick PR to fix them.

**Comment by evelinec** [comment]
Most of these issues had been addressed, except for one, that'll be reconsidered again in issue #10. Also verified all the changes for this issue. Closed.
